// 화면이 쓰는 vue-smartview 요소만 등록한다 (요소별 진입점).
// 모든 요소를 등록하는 register() 대신 쓴다: 쓰지 않는 요소의 코드가 번들에 들어가지 않게.
// 화면에 새 요소를 쓰면 여기에 더한다 (elements.test.ts 가 빠진 요소를 찾는다).
import 'vue-smartview/elements/smartview-app-shell'
import 'vue-smartview/elements/smartview-badge'
import 'vue-smartview/elements/smartview-button'
import 'vue-smartview/elements/smartview-card'
import 'vue-smartview/elements/smartview-checkbox'
import 'vue-smartview/elements/smartview-checkbox-button-group'
import 'vue-smartview/elements/smartview-checkbox-toggle'
import 'vue-smartview/elements/smartview-combobox'
import 'vue-smartview/elements/smartview-data-table'
import 'vue-smartview/elements/smartview-empty-state'
import 'vue-smartview/elements/smartview-filter-bar'
import 'vue-smartview/elements/smartview-hint-banner'
import 'vue-smartview/elements/smartview-info-list'
import 'vue-smartview/elements/smartview-input'
import 'vue-smartview/elements/smartview-login'
import 'vue-smartview/elements/smartview-modal'
import 'vue-smartview/elements/smartview-multi-picklist'
import 'vue-smartview/elements/smartview-page-header'
import 'vue-smartview/elements/smartview-password-field'
import 'vue-smartview/elements/smartview-prompt'
import 'vue-smartview/elements/smartview-refreshed-at'
import 'vue-smartview/elements/smartview-repeatable-rows'
import 'vue-smartview/elements/smartview-spinner'
import 'vue-smartview/elements/smartview-stat-card'
import 'vue-smartview/elements/smartview-state-notice'
import 'vue-smartview/elements/smartview-tabs'
import 'vue-smartview/elements/smartview-textarea'
